version: '3'

networks:
  internal:
    external: false

services:
  ## 
  ## Archiver
  ##
  archiver:
    image: archive-core:dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: archiver
    env_file: .env
    networks:
      - internal
    command:
      - '/bin/bash'
      - '-c'
      - make test
